development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: maza_app_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: maza_app_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: maza_app_production